"""initial schema

Revision ID: 6dd941dd34f6
Revises: 
Create Date: 2026-08-04 09:16:03.107982
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_connection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ldaps_url', sa.String(length=255), nullable=True),
    sa.Column('base_dn', sa.String(length=255), nullable=True),
    sa.Column('bind_account', sa.String(length=128), nullable=True),
    sa.Column('bind_secret_ref', sa.String(length=255), nullable=True),
    sa.Column('allowed_group', sa.String(length=255), nullable=True),
    sa.Column('id_attribute', sa.String(length=32), nullable=False),
    sa.Column('sync_interval', sa.String(length=16), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_result', sa.String(length=255), nullable=True),
    sa.Column('seed_admin_guid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_connection'))
    )
    op.create_table('billing_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_endpoint', sa.String(length=255), nullable=True),
    sa.Column('scp_account_id', sa.String(length=32), nullable=True),
    sa.Column('access_key', sa.String(length=128), nullable=True),
    sa.Column('secret_ref', sa.String(length=255), nullable=True),
    sa.Column('collect_interval', sa.String(length=16), nullable=True),
    sa.Column('monthly_alert_krw', sa.BigInteger(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_config'))
    )
    op.create_table('billing_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('condition', sa.String(length=255), nullable=False),
    sa.Column('mapping_label', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_rule'))
    )
    op.create_table('billing_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('dimension', sa.String(length=64), nullable=True),
    sa.Column('cost_krw', sa.BigInteger(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_snapshot'))
    )
    op.create_table('chargeback_rate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource', sa.String(length=16), nullable=False),
    sa.Column('rate_krw', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chargeback_rate')),
    sa.UniqueConstraint('resource', name=op.f('uq_chargeback_rate_resource'))
    )
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('slurmrestd_url', sa.String(length=255), nullable=True),
    sa.Column('api_version', sa.String(length=16), nullable=True),
    sa.Column('auth_method', sa.String(length=16), nullable=True),
    sa.Column('login_node', sa.String(length=128), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=True),
    sa.Column('ssh_account', sa.String(length=64), nullable=True),
    sa.Column('group_path_tpl', sa.String(length=255), nullable=True),
    sa.Column('scratch_path_tpl', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cluster')),
    sa.UniqueConstraint('name', name=op.f('uq_cluster_name'))
    )
    op.create_table('license_server',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('host', sa.String(length=128), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('vendor_daemon', sa.String(length=64), nullable=True),
    sa.Column('collect_interval', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('last_check_result', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_license_server')),
    sa.UniqueConstraint('name', name=op.f('uq_license_server_name'))
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission')),
    sa.UniqueConstraint('code', name=op.f('uq_permission_code'))
    )
    op.create_table('portal_setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poll_interval_sec', sa.Integer(), nullable=False),
    sa.Column('session_timeout_min', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=128), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_sender', sa.String(length=128), nullable=True),
    sa.Column('webhook_url', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_setting'))
    )
    op.create_table('report_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipients', sa.String(length=512), nullable=True),
    sa.Column('cycle', sa.String(length=16), nullable=True),
    sa.Column('format', sa.String(length=8), nullable=True),
    sa.Column('scope', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_schedule'))
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('code', name=op.f('uq_role_code'))
    )
    op.create_table('cluster_credential',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], name=op.f('fk_cluster_credential_cluster_id_cluster')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cluster_credential'))
    )
    op.create_table('license_feature_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=128), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('in_use', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['license_server.id'], name=op.f('fk_license_feature_snapshot_server_id_license_server')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_license_feature_snapshot'))
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name=op.f('fk_role_permission_permission_id_permission')),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_role_permission_role_id_role')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permission'))
    )
    op.create_table('user',
    sa.Column('ad_object_guid', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('default_cluster_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notify_prefs', sa.JSON(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_cluster_id'], ['cluster.id'], name=op.f('fk_user_default_cluster_id_cluster')),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_user_role_id_role')),
    sa.PrimaryKeyConstraint('ad_object_guid', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor_guid', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_cluster_id', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['actor_guid'], ['user.ad_object_guid'], name=op.f('fk_audit_log_actor_guid_user')),
    sa.ForeignKeyConstraint(['target_cluster_id'], ['cluster.id'], name=op.f('fk_audit_log_target_cluster_id_cluster')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_table('interactive_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_guid', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('app_type', sa.String(length=16), nullable=False),
    sa.Column('slurm_job_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('node_host', sa.String(length=128), nullable=True),
    sa.Column('node_port', sa.Integer(), nullable=True),
    sa.Column('connect_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('terminated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], name=op.f('fk_interactive_session_cluster_id_cluster')),
    sa.ForeignKeyConstraint(['user_guid'], ['user.ad_object_guid'], name=op.f('fk_interactive_session_user_guid_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactive_session'))
    )
    op.create_table('job_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.ad_object_guid'], name=op.f('fk_job_template_created_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_template'))
    )
    op.create_table('notice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('target_cluster_id', sa.Integer(), nullable=True),
    sa.Column('banner_enabled', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.ad_object_guid'], name=op.f('fk_notice_created_by_user')),
    sa.ForeignKeyConstraint(['target_cluster_id'], ['cluster.id'], name=op.f('fk_notice_target_cluster_id_cluster')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notice'))
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('requester_guid', sa.String(length=36), nullable=False),
    sa.Column('assignee_guid', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_guid'], ['user.ad_object_guid'], name=op.f('fk_ticket_assignee_guid_user')),
    sa.ForeignKeyConstraint(['requester_guid'], ['user.ad_object_guid'], name=op.f('fk_ticket_requester_guid_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket'))
    )
    op.create_table('user_ssh_key',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_guid', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_guid'], ['user.ad_object_guid'], name=op.f('fk_user_ssh_key_user_guid_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_ssh_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ssh_key')
    op.drop_table('ticket')
    op.drop_table('notice')
    op.drop_table('job_template')
    op.drop_table('interactive_session')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('role_permission')
    op.drop_table('license_feature_snapshot')
    op.drop_table('cluster_credential')
    op.drop_table('role')
    op.drop_table('report_schedule')
    op.drop_table('portal_setting')
    op.drop_table('permission')
    op.drop_table('license_server')
    op.drop_table('cluster')
    op.drop_table('chargeback_rate')
    op.drop_table('billing_snapshot')
    op.drop_table('billing_rule')
    op.drop_table('billing_config')
    op.drop_table('ad_connection')
    # ### end Alembic commands ###
